const SET_PLAYER = 'SET_PLAYER'
const SET_MONSTERS = 'SET_MONSTERS'
const PICK_POSITION = 'PICK_POSITION'
const UPDATE_BOARD = 'UPDATE_BOARD'
const START = 'START'
const STOP = 'STOP'
const MOVE = 'MOVE'
const TICK = 'TICK'
const RESET = 'RESET'
export {
  SET_PLAYER,
  SET_MONSTERS,
  PICK_POSITION,
  UPDATE_BOARD,
  START,
  STOP,
  MOVE,
  TICK,
  RESET
}
